services:
  postgres_kdg_db:
    image: postgres:15.8-alpine
    restart: always
    environment:
      POSTGRES_DB: 'kdg_db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5434:5432'
    networks:
      - backend
    volumes:
      - /kdg/postgres/data:/var/lib/postgresql/data

  kdg_rabbitmq:
    image: rabbitmq:4.0.1-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672" #AMQP
      - "15672:15672" #MGMT
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
    volumes:
      - /kdg/rabbitmq/data/:/var/lib/rabbitmq/
      - /kdg/rabbitmq/log/:/var/log/rabbitmq/

  kdg_idp_postgres:
    image: postgres:15.8-alpine
    volumes:
      - /kdg/idp/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - kc

  kdg_idp_keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=kdg_idp_postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    command: start-dev
    ports:
      - "8180:8080"
    depends_on:
      - kdg_idp_postgres
    networks:
      - kc

networks:
  kc:
    name: kc-network
    driver: bridge
  backend:
    name: back-network
    driver: bridge